spring:
  datasource:
    #url: jdbc:oracle:thin:@39.106.213.8:1521:orcl
    url: jdbc:mysql://rm-2ze5f9v56c119p8522o.mysql.rds.aliyuncs.com:3306/electroinc?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: TIANrm104895
    username: jiana
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,log4j
    # maxPoolPreparedStatementPerConnectionSize: 20
    # useGlobalDataSourceStat: true
    # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
#  activiti:
#    history-level: full
#    db-history-used: true
#    database-schema-update: true
    #database-schema: activiti
server:
  port: 8001
  servlet:
    context-path: /electronic



mybatis:
  # 指定全局配置文件位置E:\electronic-work\electronic-admin\src\main\resources\mybatis\mybatis-config.xml
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml,classpath*:mybatis/smapper/*.xml
  type-aliases-super-type: